from pathlib import Path

files = {
    ".gitattributes": """*.sh text eol=lf
*.sql text eol=lf
*.md text eol=lf
.gitignore text eol=lf
.gitattributes text eol=lf
""",

    ".gitignore": """# Logs generated by scripts
logs/
*.log

# Temporary Pagila clone
pagila/

# Temporary files
*.tmp
*.bak
.DS_Store

# Local configuration
.env
.vscode/
""",

    "README.md": """# PostgreSQL Pagila Security Automation

Laboratorio tecnico de automatizacion, seguridad e integridad en PostgreSQL utilizando la base de datos de ejemplo Pagila.

El proyecto prepara la base de datos, crea roles y usuarios, aplica permisos, genera una vista de inventario, configura un trigger de control y ejecuta tareas basicas de mantenimiento mediante Bash y SQL.

> [!NOTE]
> Este repositorio esta planteado como practica tecnica de administracion de PostgreSQL. No esta pensado como despliegue de produccion.

## Objetivo

Demostrar tareas de administracion de PostgreSQL aplicando automatizacion, control de permisos, seguridad basica, reglas de integridad y mantenimiento de base de datos.

## Que demuestra este proyecto

- Automatizacion de tareas de administracion en PostgreSQL.
- Carga de una base de datos de ejemplo.
- Separacion de permisos mediante roles y usuarios.
- Aplicacion de permisos sobre base de datos, esquema, tablas y secuencias.
- Creacion de una vista de inventario.
- Implementacion de un trigger de integridad.
- Ejecucion de mantenimiento con VACUUM ANALYZE y REINDEX.
- Organizacion de una practica tecnica en formato de repositorio profesional.

## Tecnologias utilizadas

- Ubuntu Server 24.04
- PostgreSQL
- Pagila
- Bash scripting
- SQL
- PL/pgSQL
- Git y GitHub

## Estructura del repositorio

    postgresql-pagila-security-automation/
    |-- README.md
    |-- .gitignore
    |-- .gitattributes
    |-- scripts/
    |   |-- setup.sh
    |   |-- prepare-pagila.sh
    |   |-- maintenance.sh
    |-- sql/
    |   |-- 01-roles.sql
    |   |-- 02-permissions.sql
    |   |-- 03-views.sql
    |   |-- 04-triggers.sql
    |-- docs/
    |   |-- memoria.md

## Funcionamiento general

El script principal es:

    ./scripts/setup.sh

Este script ejecuta el proceso completo:

1. Prepara la base de datos Pagila.
2. Crea roles y usuarios.
3. Aplica permisos.
4. Crea una vista de inventario.
5. Crea un trigger de integridad.
6. Genera un log de ejecucion.

El script maintenance.sh ejecuta tareas basicas de mantenimiento sobre tablas principales.

## Requisitos previos

Instalar dependencias:

    sudo apt update
    sudo apt install -y postgresql postgresql-contrib git

Comprobar PostgreSQL:

    sudo systemctl status postgresql

> [!IMPORTANT]
> Los scripts usan sudo -u postgres, por lo que deben ejecutarse en una maquina donde PostgreSQL este instalado localmente y el usuario tenga permisos de administracion.

## Ejecucion

Dar permisos de ejecucion:

    chmod +x scripts/setup.sh
    chmod +x scripts/prepare-pagila.sh
    chmod +x scripts/maintenance.sh

Ejecutar la configuracion completa:

    ./scripts/setup.sh

Ejecutar mantenimiento:

    ./scripts/maintenance.sh

> [!TIP]
> Ejecuta los scripts desde la raiz del repositorio, porque usan rutas relativas hacia scripts/ y sql/.

## Scripts incluidos

### scripts/setup.sh

Script principal. Ejecuta la preparacion de Pagila y despues aplica los scripts SQL en orden.

### scripts/prepare-pagila.sh

Clona Pagila, elimina una instalacion anterior si existe, crea la base de datos y carga esquema y datos.

### scripts/maintenance.sh

Ejecuta VACUUM ANALYZE y REINDEX sobre tablas importantes.

## Scripts SQL

### sql/01-roles.sql

Crea roles de grupo y usuarios de laboratorio.

### sql/02-permissions.sql

Revoca permisos generales y aplica permisos especificos por rol.

### sql/03-views.sql

Crea la vista vista_inventario para consultar disponibilidad de peliculas por tienda.

### sql/04-triggers.sql

Crea una funcion y un trigger que bloquea alquileres si el cliente tiene deuda o alquileres antiguos pendientes.

## Logs

Los logs se generan dentro de la carpeta logs/, que no se sube al repositorio.

## Documentacion completa

La memoria tecnica se encuentra en:

    docs/memoria.md

## Nota de seguridad

> [!WARNING]
> Las contrasenas incluidas en los SQL son placeholders de laboratorio. En produccion se deberian usar variables de entorno o un gestor de secretos.
""",

    "docs/memoria.md": """# Memoria tecnica - PostgreSQL Pagila Security Automation

## 1. Resumen

Este proyecto consiste en automatizar tareas basicas de administracion, seguridad e integridad en PostgreSQL usando la base de datos de ejemplo Pagila.

El repositorio incluye scripts Bash y SQL para preparar la base de datos, crear roles y usuarios, aplicar permisos, crear una vista de inventario, configurar un trigger de control y ejecutar tareas basicas de mantenimiento.

La idea principal es tener un laboratorio reproducible, ordenado y facil de entender, con una estructura parecida a la de un repositorio profesional.

## 2. Entorno utilizado

La practica esta pensada para ejecutarse en una maquina Linux con PostgreSQL instalado localmente.

Entorno previsto:

- Ubuntu Server 24.04
- PostgreSQL
- Base de datos Pagila
- Bash
- SQL
- PL/pgSQL
- Git y GitHub

Los scripts usan el usuario postgres mediante sudo, por lo que el usuario que ejecute la practica debe tener permisos de administracion.

## 3. Estructura del repositorio

    postgresql-pagila-security-automation/
    |-- README.md
    |-- .gitignore
    |-- .gitattributes
    |-- scripts/
    |   |-- setup.sh
    |   |-- prepare-pagila.sh
    |   |-- maintenance.sh
    |-- sql/
    |   |-- 01-roles.sql
    |   |-- 02-permissions.sql
    |   |-- 03-views.sql
    |   |-- 04-triggers.sql
    |-- docs/
    |   |-- memoria.md

## 4. Instalacion de dependencias

Antes de ejecutar la practica, se deben instalar PostgreSQL y Git:

    sudo apt update
    sudo apt install -y postgresql postgresql-contrib git

Despues se comprueba que el servicio de PostgreSQL este activo:

    sudo systemctl status postgresql

## 5. Funcionamiento general

El script principal del proyecto es:

    ./scripts/setup.sh

Este script ejecuta el proceso completo de configuracion:

1. Ejecuta el script de preparacion de Pagila.
2. Clona el repositorio de Pagila.
3. Elimina una base de datos anterior si ya existia.
4. Crea de nuevo la base de datos pagila.
5. Carga el esquema y los datos.
6. Ejecuta los scripts SQL en orden.
7. Guarda la salida en logs/setup.log.

El orden es importante porque primero debe existir la base de datos y despues se aplican roles, permisos, vistas y triggers.

## 6. Preparacion de Pagila

Archivo:

    scripts/prepare-pagila.sh

Este script prepara la base de datos desde cero.

Tareas principales:

- Clonar el repositorio de Pagila.
- Eliminar la carpeta local pagila si ya existia.
- Eliminar la base de datos pagila si ya estaba creada.
- Crear una nueva base de datos pagila.
- Cargar el esquema de Pagila.
- Cargar los datos de Pagila.

## 7. Roles y usuarios

Archivo:

    sql/01-roles.sql

Este script crea roles de grupo y usuarios de laboratorio.

Roles creados:

- grup_gerencia
- grup_atencio

Usuarios creados:

- daxxmanager
- daxxstaff

Las contrasenas incluidas son placeholders y no deben usarse en produccion.

## 8. Permisos

Archivo:

    sql/02-permissions.sql

Este script revoca permisos generales y aplica permisos concretos segun el perfil de cada rol.

La idea es aplicar el principio de minimos privilegios.

## 9. Vista de inventario

Archivo:

    sql/03-views.sql

Este script crea la vista vista_inventario.

La vista permite consultar informacion de peliculas e inventario por tienda.

Comprobacion de ejemplo:

    sudo -u postgres psql -d pagila -c "SELECT * FROM vista_inventario LIMIT 10;"

## 10. Trigger de integridad

Archivo:

    sql/04-triggers.sql

Este script crea una funcion y un trigger para controlar nuevos alquileres.

El trigger impide insertar un nuevo alquiler si el cliente tiene alquileres pendientes de mas de 30 dias o deuda pendiente.

## 11. Mantenimiento

Archivo:

    scripts/maintenance.sh

Este script ejecuta tareas basicas de mantenimiento sobre tablas importantes:

- rental
- inventory
- film

Operaciones utilizadas:

    VACUUM ANALYZE;
    REINDEX TABLE;

La salida se guarda en logs/maintenance.log.

## 12. Comprobaciones

Durante la practica se comprobaron estos puntos:

- PostgreSQL instalado y activo.
- Base de datos pagila creada correctamente.
- Esquema y datos cargados.
- Roles y usuarios creados.
- Permisos aplicados.
- Vista vista_inventario funcionando.
- Trigger creado correctamente.
- Script de mantenimiento ejecutado.
- Logs generados correctamente.

Comprobaciones utiles:

    sudo -u postgres psql -c "\\l"
    sudo -u postgres psql -d pagila -c "\\dt"
    sudo -u postgres psql -d pagila -c "\\du"
    sudo -u postgres psql -d pagila -c "SELECT * FROM vista_inventario LIMIT 10;"

## 13. Seguridad

Las contrasenas del laboratorio son valores placeholder.

En un entorno real se deberian usar variables de entorno, ficheros de configuracion no versionados o un gestor de secretos.

## 14. Resultado final

El resultado final es un laboratorio reproducible de PostgreSQL que demuestra automatizacion, administracion basica, control de permisos, vistas, triggers y mantenimiento de tablas.
""",

    "scripts/setup.sh": """#!/bin/bash

set -euo pipefail

DB_NAME="pagila"
LOG_DIR="logs"
LOG="$LOG_DIR/setup.log"

mkdir -p "$LOG_DIR"

exec > >(tee -a "$LOG") 2>&1

echo "=================================="
echo "INICIO DE CONFIGURACION DE PAGILA"
echo "=================================="

echo "Paso 1: preparar base de datos Pagila"
bash scripts/prepare-pagila.sh

echo "Paso 2: crear roles y usuarios"
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "$DB_NAME" -f sql/01-roles.sql

echo "Paso 3: aplicar permisos"
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "$DB_NAME" -f sql/02-permissions.sql

echo "Paso 4: crear vista de inventario"
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "$DB_NAME" -f sql/03-views.sql

echo "Paso 5: crear trigger de integridad"
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "$DB_NAME" -f sql/04-triggers.sql

echo "=================================="
echo "CONFIGURACION TERMINADA"
echo "=================================="
""",

    "scripts/prepare-pagila.sh": """#!/bin/bash

set -euo pipefail

PAGILA_REPO="https://github.com/devrimgunduz/pagila.git"
DB_NAME="pagila"

echo "Clonando repositorio de Pagila"

if [ -d "pagila" ]; then
    echo "El directorio pagila ya existe, eliminandolo"
    rm -rf pagila
fi

git clone "$PAGILA_REPO" pagila

echo "Eliminando base de datos anterior si existe"
sudo -u postgres dropdb --if-exists "$DB_NAME"

echo "Creando base de datos $DB_NAME"
sudo -u postgres createdb "$DB_NAME"

echo "Cargando esquema"
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "$DB_NAME" -f pagila/pagila-schema.sql

echo "Cargando datos"
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "$DB_NAME" -f pagila/pagila-insert-data.sql

echo "Pagila preparada correctamente"
""",

    "scripts/maintenance.sh": """#!/bin/bash

set -euo pipefail

DB_NAME="pagila"
LOG_DIR="logs"
LOG="$LOG_DIR/maintenance.log"

mkdir -p "$LOG_DIR"

exec > >(tee -a "$LOG") 2>&1

echo "========================="
echo "INICIO DEL MANTENIMIENTO"
echo "========================="

TABLES=("rental" "inventory" "film")

for TABLE in "${TABLES[@]}"; do
    echo "Ejecutando VACUUM ANALYZE en $TABLE"
    sudo -u postgres psql -v ON_ERROR_STOP=1 -d "$DB_NAME" -c "VACUUM ANALYZE $TABLE;"
done

for TABLE in "${TABLES[@]}"; do
    echo "Ejecutando REINDEX en $TABLE"
    sudo -u postgres psql -v ON_ERROR_STOP=1 -d "$DB_NAME" -c "REINDEX TABLE $TABLE;"
done

echo "Mantenimiento terminado correctamente"
""",

    "sql/01-roles.sql": """-- Remove users and roles if they already exist
DROP ROLE IF EXISTS daxxmanager;
DROP ROLE IF EXISTS daxxstaff;
DROP ROLE IF EXISTS grup_gerencia;
DROP ROLE IF EXISTS grup_atencio;

-- Create group roles without login
CREATE ROLE grup_gerencia NOLOGIN;
CREATE ROLE grup_atencio NOLOGIN;

-- Create lab users with placeholder passwords
CREATE USER daxxmanager WITH PASSWORD 'CHANGE_ME_MANAGER_PASSWORD';
CREATE USER daxxstaff WITH PASSWORD 'CHANGE_ME_STAFF_PASSWORD';

-- Assign users to their groups
GRANT grup_gerencia TO daxxmanager;
GRANT grup_atencio TO daxxstaff;
""",

    "sql/02-permissions.sql": """-- Revoke general permissions
REVOKE ALL PRIVILEGES ON DATABASE pagila FROM public;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM public;

-- Allow connection to the database
GRANT CONNECT ON DATABASE pagila TO grup_gerencia;
GRANT CONNECT ON DATABASE pagila TO grup_atencio;

-- Allow usage of the public schema
GRANT USAGE ON SCHEMA public TO grup_gerencia;
GRANT USAGE ON SCHEMA public TO grup_atencio;

-- Management permissions
GRANT SELECT, INSERT, UPDATE ON TABLE film TO grup_gerencia;
GRANT SELECT, INSERT, UPDATE ON TABLE inventory TO grup_gerencia;
GRANT SELECT, INSERT, UPDATE ON TABLE rental TO grup_gerencia;

-- Staff read permissions
GRANT SELECT ON TABLE film TO grup_atencio;
GRANT SELECT ON TABLE inventory TO grup_atencio;

-- Staff rental permissions
GRANT SELECT, INSERT ON TABLE rental TO grup_atencio;
GRANT UPDATE (return_date, last_update) ON TABLE rental TO grup_atencio;

-- Sequence permissions
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO grup_gerencia;
GRANT USAGE, SELECT ON SEQUENCE rental_rental_id_seq TO grup_atencio;
""",

    "sql/03-views.sql": """DROP VIEW IF EXISTS vista_inventario;

CREATE VIEW vista_inventario AS
SELECT
    f.title AS titulo,
    i.store_id AS tienda,
    COUNT(i.inventory_id) AS cantidad_total,
    SUM(
        CASE
            WHEN inventory_in_stock(i.inventory_id) THEN 1
            ELSE 0
        END
    ) AS cantidad_disponible
FROM film f
JOIN inventory i
    ON f.film_id = i.film_id
GROUP BY
    f.title,
    i.store_id
ORDER BY
    f.title,
    i.store_id;

GRANT SELECT ON vista_inventario TO grup_atencio;
GRANT SELECT ON vista_inventario TO grup_gerencia;
""",

    "sql/04-triggers.sql": """CREATE OR REPLACE FUNCTION public.get_customer_balance(
    p_customer_id integer,
    p_effective_date timestamp with time zone
)
RETURNS numeric
LANGUAGE plpgsql
AS $function$
DECLARE
    v_rentfees NUMERIC(10,2);
    v_overfees NUMERIC(10,2);
    v_payments NUMERIC(10,2);
BEGIN
    SELECT COALESCE(SUM(f.rental_rate), 0)
    INTO v_rentfees
    FROM film f
    JOIN inventory i
        ON f.film_id = i.film_id
    JOIN rental r
        ON i.inventory_id = r.inventory_id
    WHERE r.rental_date <= p_effective_date
      AND r.customer_id = p_customer_id;

    SELECT COALESCE(SUM(
        CASE
            WHEN r.return_date IS NOT NULL
             AND (r.return_date::date - r.rental_date::date) > f.rental_duration
            THEN ((r.return_date::date - r.rental_date::date) - f.rental_duration)::numeric
            ELSE 0::numeric
        END
    ), 0)
    INTO v_overfees
    FROM rental r
    JOIN inventory i
        ON i.inventory_id = r.inventory_id
    JOIN film f
        ON f.film_id = i.film_id
    WHERE r.rental_date <= p_effective_date
      AND r.customer_id = p_customer_id;

    SELECT COALESCE(SUM(p.amount), 0)
    INTO v_payments
    FROM payment p
    WHERE p.payment_date <= p_effective_date
      AND p.customer_id = p_customer_id;

    RETURN v_rentfees + v_overfees - v_payments;
END;
$function$;

DROP TRIGGER IF EXISTS trigger_comprobar_alquiler ON rental;
DROP FUNCTION IF EXISTS comprobar_alquiler();

CREATE OR REPLACE FUNCTION comprobar_alquiler()
RETURNS TRIGGER AS $$
DECLARE
    alquileres_pendientes INTEGER;
    deuda_cliente NUMERIC(10,2);
BEGIN
    SELECT COUNT(*)
    INTO alquileres_pendientes
    FROM rental
    WHERE customer_id = NEW.customer_id
      AND return_date IS NULL
      AND rental_date < CURRENT_TIMESTAMP - INTERVAL '30 days';

    IF alquileres_pendientes > 0 THEN
        RAISE EXCEPTION
            'No se puede crear el alquiler. El cliente % tiene alquileres pendientes de hace mas de 30 dias.',
            NEW.customer_id;
    END IF;

    SELECT COALESCE(get_customer_balance(NEW.customer_id, CURRENT_TIMESTAMP), 0)
    INTO deuda_cliente;

    IF deuda_cliente > 0 THEN
        RAISE EXCEPTION
            'No se puede crear el alquiler. El cliente % tiene una deuda pendiente de %.',
            NEW.customer_id,
            deuda_cliente;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_comprobar_alquiler
BEFORE INSERT ON rental
FOR EACH ROW
EXECUTE FUNCTION comprobar_alquiler();
"""
}

for name, content in files.items():
    path = Path(name)
    path.parent.mkdir(parents=True, exist_ok=True)
    clean = content.replace("\r\n", "\n").replace("\r", "\n").rstrip() + "\n"
    path.write_bytes(clean.encode("utf-8"))

print("Repository files rebuilt with UTF-8 and LF line endings.")